WIN_WIDTH = 800
WIN_HEIGHT = 640
ZOOM_SCALE = 1
FPS = 120
CAM_WIDTH = WIN_WIDTH // ZOOM_SCALE
CAM_HEIGHT = WIN_HEIGHT // ZOOM_SCALE
SCROLL_LIMIT_HORIZON = WIN_WIDTH // 10 // ZOOM_SCALE
SCROLL_LIMIT_VERTICAL = WIN_HEIGHT // 10 // ZOOM_SCALE
SCROLL_SPEED = 2 // ZOOM_SCALE
PADDING_WIDTH = WIN_WIDTH // 2 // ZOOM_SCALE
PADDING_HEIGHT = WIN_HEIGHT // 2 // ZOOM_SCALE
BACKGROUND_WIDTH = (WIN_WIDTH + PADDING_WIDTH) // ZOOM_SCALE
BACKGROUND_HEIGHT = (WIN_HEIGHT + PADDING_HEIGHT) // ZOOM_SCALE
PLAYER_WIDTH = 4*WIN_WIDTH//25//ZOOM_SCALE
PLAYER_HEIGHT = 5*WIN_HEIGHT//25//ZOOM_SCALE
TILESIZE = 1
PLAYER_LAYER = 2
PLAYER_SPEED = 5

BACKGROUND_LAYER = 1



RED = (255, 0, 0)
BLACK = (0, 0, 0)